### ISSUE TITLE
Hidden Nameplates show "nan"

### ISSUE THREAD

**Issue by lorem-ipsum-dolor-sit** [AKile9V/Gigancement#2]
When the "Enable Interact Key"-Option is activated. Intractable Elements, like Herbs or Ores, get a hidden Nameplate. The Giganecement-Option, "Health on Enemy Nameplates", prints a "nan" on them.

---

![image](https://github.com/user-attachments/assets/7c8b3a4e-8830-497b-bcad-34f0c0d26747)

---

A small fix in [`nameplates.lua`](https://github.com/AKile9V/Gigancement/blob/main/nameplates.lua#L44-L47) could solve it.

```lua
if hpHealth == 0/0 then
  return
end
```

**Comment by AKile9V** [comment]
Interesting bug, those hidden nameplates have 0hp and I'm dividing zero by zero when calculating the percentage... Thanks for reporting it! Will be fixed in the next update

**Comment by lorem-ipsum-dolor-sit** [comment]
Works perfect, thanks!
